# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "uv"
    target-branch: "staging"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    target-branch: "staging"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    target-branch: "staging"
    directory: "/2024-frontend"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
