# https://github.com/kentaro-m/auto-assign-action
# config here: .github/auto_assign.yml

name: PR Auto Reviewers (team) & Assignee (author)

on:
  pull_request:
    types: [opened, ready_for_review, reopened]  # will not run on drafts

jobs:
  add-reviews:
    runs-on: ubuntu-slim
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
